### ISSUE TITLE
Sound alert & bugs

### ISSUE THREAD

**Issue by Raginize** [Flexxkii/Hack-Game-Medal-of-Honor-progress-bar#1]
Hello there,

I've noticed some bugs as i mentioned you before;

1) experience bar out of profile would be useful (it can't use milestone function out of profile screen, so it causes errors, also if you use hfx extension it causes 2 total progress bar)

fixed this, made a change at the ending of code.

2) disable hotkeys at "gamecp.php?action=terminal" page

good news, fixed this too :) New logkey function added.

3) Z key selects job 22, not last completed job

Also, I've found an tampermonkey script that has sound alerts, maybe it'll help about adding notification feature.

There's script;
https://greasyfork.org/en/scripts/9247-gor-bottols/code

**Comment by Flexxkii** [comment]
Thank you for pointing this out!
I've merged your fix :D
